[[news]]
date = "2026-09"
content = "Started PhD studies at Tongji University"

[[news]]
date = "2026-04"
content = "Our work Plotania: Exploring Transparency Trade-offs in AI Co-Writing Through Virtual Readers and Transparent Attribution was accepted at CHI 2026 🎉"

[[news]]
date = "2025-11"
content = "Started RA work at City University of Hong Kong"

[[news]]
date = "2025-04"
content = "Our work IntentPrism: Human-AI Intent Manifestation for Web Information Foraging was accepted at CHI 2025 🎉"