[[news]]
date = "2026-09"
content = "在同济大学开始博士学习"

[[news]]
date = "2026-04"
content = "我们的工作Plotania: Exploring Transparency Trade-offs in AI Co-Writing Through Virtual Readers and Transparent Attribution被CHI2026接收了 🎉"

[[news]]
date = "2025-11"
content = "在香港城市大学开始RA工作"

[[news]]
date = "2025-04"
content = "我们的工作IntentPrism: Human-AI Intent Manifestation for Web Information Foraging被CHI2025接收了 🎉"